### ISSUE TITLE
Cannot scan barcode

### ISSUE THREAD

**Issue by vietcuong122** [darryncampbell/DataWedgeReactNative#29]
I have just clone example project and replace this
<img width="820" alt="Screen Shot 2021-05-11 at 11 09 45 AM" src="https://user-images.githubusercontent.com/48023195/117757026-775ef280-b249-11eb-9d04-1bfa8965b9b7.png">
But when press on "Scan" button it nothing happened.
Here are the logs:
<img width="996" alt="Screen Shot 2021-05-11 at 11 11 10 AM" src="https://user-images.githubusercontent.com/48023195/117757095-99587500-b249-11eb-9292-2e5e4966eac3.png">

**Comment by darryncampbell** [comment]
By modifying the highlighted line you will cause the DataWedge profile "ZebraReactNativeDemo" to no longer be associated with your application as that line is where you specify the package name which the profile is associated with.  

What is probably happening is that DataWedge will fall back to the default profile because it cannot find a profile associated with your app package and since the default profile does not know how to send data to your app, your app will never receive barcode scans.

Does that make sense?  What were you trying to achieve by changing that line?

**Comment by darryncampbell** [comment]
I ran your code and after clicking the AIInput button (to load the new view) and scanning a barcode I see `call barcode scanned` in the console output along with the barcode that was scanned.

**Comment by vietcuong122** [comment]
Thanks for your reply. I have fixed my code, and now it can be scanned successfully. But one more confused, in barcodeScanned function, I just received the scanned data and do nothing with this, but if the screen has input on focus, it will append the scanned data to the input. Do you know the reason?

**Comment by darryncampbell** [comment]
> Thanks for your reply. I have fixed my code, and now it can be scanned successfully. But one more confused, in barcodeScanned function, I just received the scanned data and do nothing with this, but if the screen has input on focus, it will append the scanned data to the input. Do you know the reason?

Please disable the KeyStroke output plugin in your DataWedge profile

**Comment by vietcuong122** [comment]
Many thanks for your help. It works nicely.
